[features]
seeds = false

[programs.localnet]
superstream = "EVAwWziymdW9hRxZR6TsSKZjisiyUsthF51tHCAE4moB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
